target 'CameraKitSample' do
	pod 'SCSDKCameraKit', '1.18.1'
	pod 'SCSDKCameraKitReferenceUI', '1.18.1'
	pod 'SCSDKCameraKitReferenceSwiftUI', '1.18.1'
	pod 'SnapSDK', '1.14.0', :subspecs => ['SCSDKCreativeKit']

	target 'CameraKitSampleTests' do
		inherit! :search_paths
	end
end

# https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1149585364
# Developers seem to have encountered an issue with using CocoaPods from Xcode 14.
# We might no longer require this work-around in a future version of CocoaPods.

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
