platform :ios, '12.0'
target 'CameraKitAlternateCarouselSample' do
	
	pod 'SCSDKCameraKit', :path => '../CameraKitSample/CameraKit/CameraKit'
	pod 'SnapSDK', '2.4.0', :subspecs => ['SCSDKCreativeKit']
	target 'CameraKitAlternateCarouselSampleTests' do
		inherit! :search_paths
	end
end